import React, { useEffect, useState } from "react";
import { Copy, Link2, MonitorUp, RefreshCw, ShieldCheck, Trash2, Unplug } from "lucide-react";
import QRCode from "qrcode";
import { createRemoteDisplay, createRemotePairing, deleteRemoteDisplay, listRemoteDisplays, revokeRemoteDisplay, updateRemoteDisplay } from "./remoteDisplays";

function Pairing({ pairing }) {
  const [qr, setQr] = useState("");
  useEffect(() => { QRCode.toDataURL(pairing?.pairingUrl || "", { width: 260, margin: 1 }).then(setQr).catch(() => setQr("")); }, [pairing?.pairingUrl]);
  if (!pairing) return null;
  return <div className="mt-3 grid gap-3 rounded-xl border border-blue-200 bg-blue-50 p-3 sm:grid-cols-[100px_1fr]">{qr && <img src={qr} alt="QR para vincular la pantalla" className="h-24 w-24 rounded-lg border bg-white p-1"/>}<div><p className="text-xs font-black text-blue-950">Código de un solo uso: <span className="tracking-[.2em]">{pairing.code}</span></p><p className="mt-1 text-[10px] text-blue-800">Vence en 10 minutos. Abrí el enlace en la TV o escaneá el QR. Una vez vinculado, el código deja de funcionar.</p><button type="button" onClick={() => navigator.clipboard?.writeText(pairing.pairingUrl)} className="mt-2 inline-flex min-h-9 items-center gap-1 rounded-lg border border-blue-300 bg-white px-3 text-[10px] font-bold text-blue-900"><Copy size={13}/>Copiar enlace</button></div></div>;
}

export function RemoteDisplayManager({ businessId, content }) {
  const [displays, setDisplays] = useState([]);
  const [name, setName] = useState("");
  const [pairing, setPairing] = useState(null);
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const refresh = async () => { try { const payload = await listRemoteDisplays(businessId); setDisplays(payload.displays || []); } catch (error) { setMessage(error.message); } };
  useEffect(() => { if (businessId) refresh(); }, [businessId]);
  const act = async (operation, success) => { setBusy(true); setMessage(""); try { const payload = await operation(); success?.(payload); await refresh(); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  return <div className="rounded-xl border border-blue-200 bg-blue-50/60 p-4"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-700 text-white"><MonitorUp size={19}/></span><div><h4 className="text-sm font-black text-blue-950">Pantallas remotas sólo publicitarias</h4><p className="mt-1 text-xs leading-5 text-blue-800">Una TV, tablet o computadora puede abrir un enlace y quedar vinculada. Sólo recibe el diseño, promociones y datos públicos. Cada pantalla conserva su propia copia.</p></div></div>
    <div className="mt-3 grid gap-2 sm:grid-cols-[minmax(0,1fr)_auto]"><input value={name} onChange={(event) => setName(event.target.value.slice(0, 80))} placeholder="Ej.: TV de la vidriera" className="min-h-10 rounded-lg border bg-white px-3 text-xs"/><button disabled={busy} type="button" onClick={() => act(() => createRemoteDisplay(businessId, name || `Pantalla ${displays.length + 1}`, content), (payload) => { setName(""); setPairing(payload.pairing); setMessage("Pantalla creada. Ahora vinculala con el código."); })} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg bg-blue-700 px-4 text-xs font-bold text-white disabled:opacity-50"><Link2 size={15}/>Crear pantalla</button></div>
    <Pairing pairing={pairing}/>
    <div className="mt-3 grid gap-2">{displays.map((display) => <div key={display.id} className="rounded-xl border bg-white p-3"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black text-gray-900">{display.name}</p><p className="mt-1 text-[10px] text-gray-500">{display.pairedDevices ? `${display.pairedDevices} dispositivo(s) vinculado(s)` : "Sin vincular"}{display.lastSeenAt ? ` · Última conexión ${new Date(display.lastSeenAt).toLocaleString("es-AR")}` : ""}</p></div><div className="flex flex-wrap gap-1.5"><button disabled={busy} type="button" onClick={() => act(() => updateRemoteDisplay(businessId, display.id, { content }), () => setMessage(`Contenido de ${display.name} actualizado.`))} className="inline-flex min-h-8 items-center gap-1 rounded-lg border px-2.5 text-[9px] font-bold"><RefreshCw size={12}/>Actualizar contenido</button><button disabled={busy} type="button" onClick={() => act(() => createRemotePairing(businessId, display.id), (payload) => setPairing(payload.pairing))} className="inline-flex min-h-8 items-center gap-1 rounded-lg border border-blue-200 text-blue-800 px-2.5 text-[9px] font-bold"><ShieldCheck size={12}/>Vincular</button><button disabled={busy || !display.pairedDevices} type="button" onClick={() => act(() => revokeRemoteDisplay(businessId, display.id), () => setMessage(`Se desvincularon los equipos de ${display.name}.`))} className="inline-flex min-h-8 items-center gap-1 rounded-lg border border-amber-200 px-2.5 text-[9px] font-bold text-amber-800 disabled:opacity-40"><Unplug size={12}/>Desvincular</button><button disabled={busy} type="button" onClick={() => window.confirm(`¿Eliminar ${display.name}?`) && act(() => deleteRemoteDisplay(businessId, display.id), () => setMessage("Pantalla eliminada."))} className="grid h-8 w-8 place-items-center rounded-lg border border-red-200 text-red-600"><Trash2 size={13}/></button></div></div></div>)}{!displays.length && <p className="rounded-lg border border-dashed border-blue-200 bg-white p-4 text-center text-xs text-gray-500">Todavía no creaste pantallas remotas.</p>}</div>
    {message && <p className="mt-3 rounded-lg bg-white px-3 py-2 text-xs text-gray-700">{message}</p>}
  </div>;
}
