BEGIN;
CREATE TABLE schema_migrations (version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE businesses (id uuid PRIMARY KEY, name text NOT NULL, status text NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users (id uuid PRIMARY KEY, business_id uuid REFERENCES businesses(id), username text NOT NULL UNIQUE, password_hash text NOT NULL, name text NOT NULL, role text NOT NULL, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE roles (id uuid PRIMARY KEY, business_id uuid NOT NULL REFERENCES businesses(id), name text NOT NULL, permissions jsonb NOT NULL DEFAULT '[]');
CREATE TABLE sessions (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), device_id text NOT NULL, refresh_hash text NOT NULL, expires_at timestamptz NOT NULL, revoked_at timestamptz);
CREATE TABLE devices (id text NOT NULL, business_id uuid NOT NULL REFERENCES businesses(id), user_id uuid REFERENCES users(id), name text, last_seen_at timestamptz, revoked_at timestamptz, PRIMARY KEY(id,business_id));
CREATE TABLE products (id text NOT NULL, business_id uuid NOT NULL REFERENCES businesses(id), data jsonb NOT NULL, version bigint NOT NULL DEFAULT 1, deleted_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id,business_id));
CREATE TABLE suppliers (id text NOT NULL, business_id uuid NOT NULL REFERENCES businesses(id), data jsonb NOT NULL, version bigint NOT NULL DEFAULT 1, deleted_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id,business_id));
CREATE TABLE customers (id text NOT NULL, business_id uuid NOT NULL REFERENCES businesses(id), data jsonb NOT NULL, version bigint NOT NULL DEFAULT 1, deleted_at timestamptz, PRIMARY KEY(id,business_id));
CREATE TABLE sales (id text NOT NULL, business_id uuid NOT NULL REFERENCES businesses(id), data jsonb NOT NULL, created_at timestamptz NOT NULL, voided_at timestamptz, PRIMARY KEY(id,business_id));
CREATE TABLE sale_lines (id uuid PRIMARY KEY, sale_id text NOT NULL, business_id uuid NOT NULL REFERENCES businesses(id), product_id text, quantity numeric NOT NULL, unit_price numeric NOT NULL, cost numeric);
CREATE TABLE cash_movements (id text NOT NULL, business_id uuid NOT NULL REFERENCES businesses(id), type text NOT NULL, amount numeric NOT NULL, data jsonb NOT NULL, created_at timestamptz NOT NULL, PRIMARY KEY(id,business_id));
CREATE TABLE expenses (id text NOT NULL, business_id uuid NOT NULL REFERENCES businesses(id), data jsonb NOT NULL, version bigint NOT NULL DEFAULT 1, PRIMARY KEY(id,business_id));
CREATE TABLE inventory_events (id text NOT NULL, business_id uuid NOT NULL REFERENCES businesses(id), kind text NOT NULL, data jsonb NOT NULL, created_at timestamptz NOT NULL, PRIMARY KEY(id,business_id));
CREATE TABLE audit_events (id bigserial PRIMARY KEY, business_id uuid NOT NULL REFERENCES businesses(id), user_id uuid, device_id text, action text NOT NULL, entity text, entity_id text, data jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE sync_operations (id uuid PRIMARY KEY, business_id uuid NOT NULL REFERENCES businesses(id), device_id text NOT NULL, cursor bigserial UNIQUE, payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX products_business_active ON products(business_id) WHERE deleted_at IS NULL;
CREATE INDEX sync_business_cursor ON sync_operations(business_id,cursor);
ALTER TABLE products ENABLE ROW LEVEL SECURITY; ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY; ALTER TABLE customers ENABLE ROW LEVEL SECURITY; ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
INSERT INTO schema_migrations(version) VALUES (1);
COMMIT;
