import React, { useMemo, useState } from "react";
import { Banknote, BellRing, Check, ClipboardList, Clock, Copy, PackageOpen, Plus, Printer, RotateCcw, Trash2, Users } from "lucide-react";
import { money } from "../../shared/domain";
import { AppSelect, PromptDialog } from "../../shared/controls";

const sections = [["lista","Lista de compras",ClipboardList],["retornables","Retornables",PackageOpen],["cambio","Cambio",Banknote],["autoconsumo","Autoconsumo",RotateCcw],["turnos","Turnos",Users],["recordatorios","Recordatorios",BellRing],["resumen","Resumen diario",Printer]];
const input = "w-full rounded-lg border px-3 py-2 text-sm";
const today = () => new Date().toISOString().slice(0,10);
const addItem = (setter, payload) => setter((prev) => [{ id: Date.now(), fecha: new Date().toISOString(), ...payload }, ...(prev || [])]);

export function SmallBusinessTools({ data, setters, identidad, preferences = {}, sectionsAllowed = sections.map(([id]) => id), staffOptions = [] }) {
  const visibleSections = sections.filter(([id]) => sectionsAllowed.includes(id));
  const [section, setSection] = useState(visibleSections[0]?.[0] || "lista");
  const [copyFallbackOpen, setCopyFallbackOpen] = useState(false);
  const [form, setForm] = useState({ texto:"", cantidad:"1", persona:"", monto:"", productId:"", nota:"", fecha:today(), hora:"09:00", proveedorId:"" });
  const set = (key,value) => setForm((prev)=>({...prev,[key]:value}));
  const clear = () => setForm({ texto:"", cantidad:"1", persona:"", monto:"", productId:"", nota:"", fecha:today(), hora:"09:00", proveedorId:"" });
  const ticketsHoy = useMemo(() => (data.tickets||[]).filter((t)=>!t.anulado&&String(t.fecha).slice(0,10)===today()),[data.tickets]);
  const gastosHoy = useMemo(() => (data.gastos||[]).filter((g)=>String(g.fecha||g.vencimiento).slice(0,10)===today()),[data.gastos]);
  const ventas = ticketsHoy.reduce((s,t)=>s+Number(t.total||0),0), gastos = gastosHoy.reduce((s,g)=>s+Number(g.monto||0),0);
  const metodos = ticketsHoy.flatMap((t)=>t.pagos?.length?t.pagos:[{metodo:t.medio,monto:t.total}]).reduce((map,p)=>({...map,[p.metodo]:(map[p.metodo]||0)+Number(p.monto||0)}),{});
  const resumen = [`CIERRE ${new Date().toLocaleDateString("es-AR")}`,`Ventas: ${money(ventas)}`,`Tickets: ${ticketsHoy.length}`,...Object.entries(metodos).map(([k,v])=>`${k}: ${money(v)}`),`Gastos: ${money(gastos)}`,`Resultado estimado: ${money(ventas-gastos)}`,`Caja actual: ${money(data.caja?.saldo||0)}`].join("\n");
  const copySummary = async () => { try { await navigator.clipboard.writeText(resumen); } catch { setCopyFallbackOpen(true); } };
  const printSummary = () => { const old=document.title;document.title="Resumen diario";window.print();document.title=old; };
  const addSelfUse = () => { const product=data.products.find((p)=>String(p.id)===String(form.productId)); const qty=Number(form.cantidad); if(!product||qty<=0)return; setters.setProducts((prev)=>prev.map((p)=>p.id!==product.id?p:{...p,...(Number(p.vitrina)>=qty?{vitrina:Number(p.vitrina)-qty}:{vitrina:0,deposito:Math.max(0,Number(p.deposito)-Math.max(0,qty-Number(p.vitrina)))})})); addItem(setters.setAutoconsumos,{productId:product.id,producto:product.nombre,cantidad:qty,usuario:identidad?.nombre,nota:form.nota});clear(); };
  const currentShift=(data.turnos||[]).find((t)=>!t.fin);
  return <div><PromptDialog open={copyFallbackOpen} title="Copiar resumen" message="Tu dispositivo no permitió copiarlo automáticamente. Seleccioná el texto y copialo manualmente." value={resumen} readOnly confirmLabel="Cerrar" onCancel={()=>setCopyFallbackOpen(false)} onConfirm={()=>setCopyFallbackOpen(false)}/><div className={visibleSections.length < 2 ? "hidden" : "mb-5"}><div className="sm:hidden"><AppSelect value={section} onChange={setSection} options={visibleSections.map(([id,label])=>({value:id,label}))}/></div><div className="hidden flex-wrap gap-2 sm:flex">{visibleSections.map(([id,label,Icon])=><button key={id} onClick={()=>setSection(id)} className={`flex min-h-10 items-center gap-2 rounded-lg border px-3 py-2 text-sm ${section===id?"bg-gray-900 text-white":"bg-white"}`}><Icon size={15}/>{label}</button>)}</div></div>
    {section==="lista"&&<Panel title="Lista de compras manual" subtitle="Para cosas que faltan aunque todavía no estén cargadas como productos."><div className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_auto]"><input value={form.texto} onChange={(e)=>set("texto",e.target.value)} placeholder="Ej.: bolsas, cinta, Coca-Cola..." className={input}/><button disabled={!form.texto.trim()} onClick={()=>{addItem(setters.setListaCompras,{texto:form.texto.trim(),cantidad:Number(form.cantidad)||1,completo:false});clear();}} className="action min-h-10 w-full justify-center sm:w-auto"><Plus size={16}/>Agregar</button></div><List items={data.listaCompras} setter={setters.setListaCompras} render={(x)=><><button onClick={()=>setters.setListaCompras(p=>p.map(i=>i.id===x.id?{...i,completo:!i.completo}:i))} className={`h-5 w-5 shrink-0 rounded border ${x.completo?"bg-green-600 text-white":""}`}>{x.completo&&<Check size={15}/>}</button><span className={`min-w-0 flex-1 break-words ${x.completo?"line-through opacity-50":""}`}>{x.texto}</span></>}/></Panel>}
    {section==="retornables"&&<Panel title="Envases y productos prestados" subtitle="Controlá botellas, cajones, sifones o mercadería pendiente de devolución."><div className="grid gap-2 sm:grid-cols-3"><input value={form.persona} onChange={(e)=>set("persona",e.target.value)} placeholder="Cliente o persona" className={input}/><input value={form.texto} onChange={(e)=>set("texto",e.target.value)} placeholder="Qué se llevó" className={input}/><div className="grid grid-cols-[minmax(0,1fr)_44px] gap-2"><input type="number" value={form.cantidad} onChange={(e)=>set("cantidad",e.target.value)} className={input}/><button disabled={!form.persona||!form.texto} onClick={()=>{addItem(setters.setRetornables,{persona:form.persona,detalle:form.texto,cantidad:Number(form.cantidad)||1,devuelto:false});clear();}} className="action min-h-10 justify-center px-0"><Plus size={16}/></button></div></div><List items={data.retornables} setter={setters.setRetornables} render={(x)=><><button onClick={()=>setters.setRetornables(p=>p.map(i=>i.id===x.id?{...i,devuelto:!i.devuelto}:i))} className={`h-5 w-5 shrink-0 rounded border ${x.devuelto?"bg-green-600 text-white":""}`}>{x.devuelto&&<Check size={15}/>}</button><span className={`min-w-0 flex-1 break-words ${x.devuelto?"line-through opacity-50":""}`}><b>{x.persona}</b> · {x.cantidad} {x.detalle}</span></>}/></Panel>}
    {section==="cambio"&&<Panel title="Control de cambio" subtitle="Anotá cuántos billetes chicos tenés y la app avisa qué denominaciones faltan."><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5">{[10,20,50,100,200,500,1000,2000,10000,20000].map((d)=><label key={d} className={`min-w-0 rounded-lg border p-2 text-xs ${Number(data.cambioCaja?.[d]||0)<3?"border-amber-300 bg-amber-50":""}`}>{money(d)}<input type="number" value={data.cambioCaja?.[d]??""} onChange={(e)=>setters.setCambioCaja((p)=>({...p,[d]:e.target.value}))} className={`${input} mt-1 min-w-0`}/><small className="mt-1 block">{Number(data.cambioCaja?.[d]||0)<3?"Falta cambio":"Disponible"}</small></label>)}</div></Panel>}
    {section==="autoconsumo"&&<Panel title="Autoconsumo" subtitle="Descuenta stock sin registrarlo como venta ni pérdida."><div data-tour="self-use-form" className="grid gap-2 sm:grid-cols-[1fr_110px_1fr_auto]"><AppSelect value={form.productId} onChange={(v)=>set("productId",v)} options={[{value:"",label:"Elegí un producto"},...data.products.map((p)=>({value:String(p.id),label:p.nombre}))]}/><input type="number" value={form.cantidad} onChange={(e)=>set("cantidad",e.target.value)} className={input}/><input value={form.nota} onChange={(e)=>set("nota",e.target.value)} placeholder="Motivo opcional" className={input}/><button data-tour="self-use-save" onClick={addSelfUse} className="action min-h-10 w-full justify-center sm:w-auto">Registrar</button></div><div data-tour="self-use-history"><List items={data.autoconsumos} setter={setters.setAutoconsumos} render={(x)=><span className="min-w-0 flex-1 break-words"><b>{x.producto}</b> · {x.cantidad} · {x.usuario}{x.nota?` · ${x.nota}`:""}</span>}/></div></Panel>}
    {section==="turnos"&&<Panel title="Turnos simples" subtitle="La lista toma automáticamente al dueño y a los empleados del negocio.">{!currentShift?<div className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_auto]"><AppSelect value={form.persona} onChange={(v)=>set("persona",v)} options={[{value:"",label:identidad?.nombre||"Elegí una persona"},...staffOptions.map((name)=>({value:name,label:name}))]}/><button onClick={()=>{addItem(setters.setTurnos,{persona:form.persona||identidad?.nombre||"Sin identificar",inicio:new Date().toISOString(),ventasInicio:ventas});clear();}} className="action min-h-10 w-full justify-center sm:w-auto">Iniciar turno</button></div>:<div className="flex flex-col items-stretch gap-3 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between"><span className="min-w-0 break-words"><b>{currentShift.persona}</b><small className="block opacity-60">Desde {new Date(currentShift.inicio).toLocaleString("es-AR")}</small></span><button onClick={()=>setters.setTurnos(p=>p.map(t=>t.id===currentShift.id?{...t,fin:new Date().toISOString(),ventas:Math.max(0,ventas-Number(t.ventasInicio||0))}:t))} className="action min-h-10 w-full justify-center sm:w-auto">Cerrar turno</button></div>}<List items={(data.turnos||[]).filter(t=>t.fin)} setter={setters.setTurnos} render={(x)=><span className="min-w-0 flex-1 break-words"><b>{x.persona}</b> · {new Date(x.inicio).toLocaleString("es-AR")} · {money(x.ventas||0)}</span>}/></Panel>}
    {section==="recordatorios"&&<Panel title="Recordatorios de proveedores" subtitle="Avisos con día y hora para repartos, pedidos o pagos."><div className="grid gap-2 sm:grid-cols-[1fr_150px_120px_auto]"><input value={form.texto} onChange={(e)=>set("texto",e.target.value)} placeholder="Ej.: pedir bebidas" className={input}/><input type="date" value={form.fecha} onChange={(e)=>set("fecha",e.target.value)} className={input}/><input type="time" value={form.hora} onChange={(e)=>set("hora",e.target.value)} className={input}/><button disabled={!form.texto} onClick={()=>{addItem(setters.setRecordatoriosProveedor,{texto:form.texto,para:form.fecha,hora:form.hora,completo:false});clear();}} className="action min-h-10 w-full justify-center sm:w-auto"><Plus size={16}/>Agregar</button></div><List items={data.recordatoriosProveedor} setter={setters.setRecordatoriosProveedor} render={(x)=><><button onClick={()=>setters.setRecordatoriosProveedor(p=>p.map(i=>i.id===x.id?{...i,completo:!i.completo}:i))} className={`h-5 w-5 shrink-0 rounded border ${x.completo?"bg-green-600 text-white":""}`}>{x.completo&&<Check size={15}/>}</button><span className={`min-w-0 flex-1 break-words ${x.completo?"line-through opacity-50":""}`}>{x.texto} · {new Date(`${x.para}T12:00`).toLocaleDateString("es-AR")}{x.hora?` · ${x.hora} h`:""}</span></>}/></Panel>}
    {section==="resumen"&&<Panel title="Resumen diario" subtitle="Copialo para WhatsApp o imprimilo como ticket."><pre className="daily-summary-print whitespace-pre-wrap break-words rounded-xl border bg-gray-50 p-3 text-sm sm:p-4">{resumen}</pre><div className="mt-3 flex flex-col gap-2 sm:flex-row sm:flex-wrap"><button onClick={copySummary} className="action min-h-10 w-full justify-center sm:w-auto"><Copy size={15}/>Copiar para WhatsApp</button>{preferences.printDailySummary?<button onClick={printSummary} className="action min-h-10 w-full justify-center sm:w-auto"><Printer size={15}/>Imprimir resumen</button>:<span className="w-full rounded-lg border px-3 py-2 text-xs opacity-65">Habilitá la impresión del resumen en Configuración → Impresión y cajón.</span>}</div></Panel>}
  </div>;
}

function Panel({title,subtitle,children}){return <div className="min-w-0 rounded-xl border bg-white p-4 sm:p-5"><h3 className="break-words font-semibold">{title}</h3><p className="mb-4 break-words text-sm opacity-60">{subtitle}</p>{children}</div>}
function List({items=[],setter,render}){return <div className="mt-4 space-y-2">{items.map((item)=><div key={item.id} className="flex min-w-0 items-start gap-3 rounded-lg border p-3 text-sm"><div className="flex min-w-0 flex-1 items-start gap-3">{render(item)}</div><button onClick={()=>setter(p=>p.filter(x=>x.id!==item.id))} className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg text-red-500"><Trash2 size={15}/></button></div>)}</div>}
